Added a template for the AI-class and tried to document all necessary functions to run the old scripts

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -4174,7 +4174,6 @@ echo "$as_me: error: SDL required" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-#AC_CHECK_LIB(SDL_net,SDLNet_Init, [], [AC_MSG_ERROR(SDL_net required)])
 
 { echo "$as_me:$LINENO: checking for inflate in -lz" >&5
 echo $ECHO_N "checking for inflate in -lz... $ECHO_C" >&6; }
@@ -4446,6 +4445,98 @@ _ACEOF
 else
   { echo "$as_me:$LINENO: WARNING: OpenGL support disabled" >&5
 echo "$as_me: WARNING: OpenGL support disabled" >&2;}
+fi
+
+
+
+{ echo "$as_me:$LINENO: checking for lua_pushboolean in -llua50" >&5
+echo $ECHO_N "checking for lua_pushboolean in -llua50... $ECHO_C" >&6; }
+if test "${ac_cv_lib_lua50_lua_pushboolean+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-llua50  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char lua_pushboolean ();
+int
+main ()
+{
+return lua_pushboolean ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_lua50_lua_pushboolean=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_lua50_lua_pushboolean=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_lua50_lua_pushboolean" >&5
+echo "${ECHO_T}$ac_cv_lib_lua50_lua_pushboolean" >&6; }
+if test $ac_cv_lib_lua50_lua_pushboolean = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBLUA50 1
+_ACEOF
+
+  LIBS="-llua50 $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: Lua 5.0 required" >&5
+echo "$as_me: error: Lua 5.0 required" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 
